name: Generate Pac-Man

on:
  workflow_dispatch: # manual

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate Pac-Man graph
        uses: platane/snk@v3
        with:
          github_user_name: iscaio
          outputs: |
            pacman-contribution-graph.svg
            pacman-contribution-graph-dark.svg

      - name: Push SVGs
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git checkout output
          git add pacman-contribution-graph*.svg
          git commit -m "Update Pac-Man" || echo "Nothing to commit"
          git push origin output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
