name: Generate Pac-Man Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *" # roda todo dia à meia-noite
  workflow_dispatch: # permite rodar manualmente

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Generate Pac-Man graph
        uses: Platane/snk@v3
        with:
          github_user_name: iscaio
          outputs: |
            pacman-contribution-graph.svg
            pacman-contribution-graph-dark.svg

      - name: Commit e push para output
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git branch -M output
          git add pacman-contribution-graph*.svg
          git commit -m "Update Pac-Man Contribution Graph" || echo "Nothing to commit"
          git push -u origin output --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
