name: Pac-Man Contribution Graph

on:
  workflow_dispatch: # Permite rodar manualmente
  schedule:
    - cron: "0 0 * * *" # Roda todo dia à meia-noite

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate Pac-Man graph
        uses: platane/snk@v3
        with:
          github_user_name: iscaio
          outputs: |
            pacman-contribution-graph.svg
            pacman-contribution-graph-dark.svg
